-- ExpenseTracker MySQL Database Setup Script
-- Run this script in MySQL to create the database

CREATE DATABASE IF NOT EXISTS expense_tracker_db;
USE expense_tracker_db;

-- The tables will be automatically created by Hibernate based on your JPA entities
-- This script is for reference and manual database creation if needed

-- Example table structure (will be auto-generated by Hibernate):
-- 
-- CREATE TABLE users (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     username VARCHAR(50) UNIQUE NOT NULL,
--     email VARCHAR(100) UNIQUE NOT NULL,
--     password VARCHAR(255) NOT NULL,
--     created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--     updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );
-- 
-- CREATE TABLE expenses (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     title VARCHAR(255) NOT NULL,
--     description TEXT,
--     amount DECIMAL(10,2) NOT NULL,
--     category VARCHAR(100) NOT NULL,
--     expense_date DATE NOT NULL,
--     created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--     updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--     user_id BIGINT NOT NULL,
--     FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
-- );

-- Grant privileges (adjust username as needed)
-- GRANT ALL PRIVILEGES ON expense_tracker_db.* TO 'root'@'localhost';
-- FLUSH PRIVILEGES;
