version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: expense_tracker_mysql
    restart: always
    environment:
      MYSQL_DATABASE: expense_tracker_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: expenseuser
      MYSQL_PASSWORD: expensepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database-setup.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: expense_tracker_phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"

volumes:
  mysql_data:
